name: CarbonRunner Test

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  check-cpu:
    runs-on: carbonrunner-32vcpu-ubuntu-2404

    steps:
      - uses: actions/checkout@v4

      - name: Show CPU Info
        run: lscpu
