name: CPU Info

on:
  push:
    branches:
      - main

jobs:
  cpu-info:
    runs-on: blacksmith-4vcpu-ubuntu-2404  # use a Blacksmith runner tag
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show CPU info
        run: lscpu
