name: webhtml

on:
  push:
  workflow_dispatch:

jobs:

  start_task_1:
    name: Start Task 1
    runs-on: blacksmith-2vcpu-ubuntu-2404
    steps:
      - name: Jalankan Task 1
        run: |
          lscpu
