name: CI on Puzl

on:
  push:
    branches:
      - main

jobs:
  show-cpu:
    runs-on: puzl-ubuntu-latest    # label runner Puzl dari dokumentasi
    steps:
      - uses: actions/checkout@v4
      - name: Show CPU Info
        run: lscpu
